export HOST=$(hostname -s)

export EDITOR=nano

export PATH="$HOME/bin:$PATH"

source ~/.zgenom/zgenom.zsh

zgenom autoupdate

if ! zgenom saved; then
	zgenom ohmyzsh
	if [[ -f ~/.dotfiles/includes/host-specific/${HOST}/zgenom ]]; then
		source ~/.dotfiles/includes/host-specific/${HOST}/zgenom
	fi
	source ~/.dotfiles/includes/zgenom

	zgenom save
fi

if [[ -f ~/.dotfiles/includes/host-specific/${HOST}/zshrc ]]; then
	source ~/.dotfiles/includes/host-specific/${HOST}/zshrc
fi

source ~/.dotfiles/includes/config
source ~/.dotfiles/includes/aliases
source ~/.dotfiles/includes/functions

if [[ -f ~/.zshrc-local ]]; then
	source ~/.zshrc-local
fi
