export HOST=$(hostname -s)

export EDITOR=nano
export DISABLE_AUTO_UPDATE=true
export XZ_DEFAULTS="-T 0"

export PATH="$HOME/bin:$PATH"

source ~/.dotfiles/zgen/zgen.zsh
if ! zgen saved; then
	zgen load robbyrussell/oh-my-zsh

	source ~/.dotfiles/includes/zgen
	if [[ -f ~/.dotfiles/includes/host-specific/${HOST}/zgen ]]; then
		source ~/.dotfiles/includes/host-specific/${HOST}/zgen
	fi

#	zgen load zsh-users/zsh-syntax-highlighting
	zgen load zdharma/fast-syntax-highlighting
	zgen load zsh-users/zsh-history-substring-search

	zgen save
fi

if [[ -f ~/.dotfiles/includes/host-specific/${HOST}/zshrc ]]; then
	source ~/.dotfiles/includes/host-specific/${HOST}/zshrc
fi

source ~/.dotfiles/includes/config
source ~/.dotfiles/includes/aliases
source ~/.dotfiles/includes/functions

if [[ -f ~/.zshrc-local ]]; then
	source ~/.zshrc-local
fi
