alias TARDIS='sudo mkdir -p /media/TARDIS && sudo mount -t ufsd UUID=7020BFDE2863E7CC /media/TARDIS -o users,nls=utf8,uid=1000,gid=1000'
alias uTARDIS='sudo umount /media/TARDIS && sudo rmdir /media/TARDIS'

export PATH="$HOME/.linuxbrew/bin:$PATH"
export PATH="$HOME/.linuxbrew/sbin:$PATH"
export MANPATH="$HOME/.linuxbrew/share/man:$MANPATH"
export INFOPATH="$HOME/.linuxbrew/share/info:$INFOPATH"

export GOPATH=/opt/Dinge/Code/go
export PATH=$GOPATH/bin:$PATH
