function weggucken() {
	for item in $*; do
		vlc --play-and-exit --rate 1.5 --scale 0.5 $item >/dev/null 2>/dev/null
		rm -i -v $item
	done
}

export ZFS_COLOR=1

export BAT_THEME="Dracula"

export GOCACHE=/tmp/go/build                    # Go build cache in tmp/memory
export GOTMPDIR=/tmp/go/tmp                     # tmp files during compile
[[ ! -d "$GOTMPDIR" ]] && mkdir -p "$GOTMPDIR"  # Make sure it exists as Go won't create it.

export PATH=$HOME/go/bin:$PATH
