function weggucken() {
	for item in $*; do
		vlc --rate 1.30 --scale 0.5 $item vlc://quit >/dev/null 2>/dev/null
		rm -i -v $item
	done
}

function goclone() {
	p=$(echo $1|sed -e 's,^git@,,' -e 's,^http://,,' -e 's,^https://,,' -e 's,.git$,,'|tr ":" "/")
	git clone $1 $p
}

export GOPATH=$HOME/projekte/gopath
export PATH=$GOPATH/bin:$PATH
